<?php

declare(strict_types=1);

use Fisharebest\Webtrees\Http\RequestHandlers\ControlPanel;
use Fisharebest\Webtrees\I18N;
use Hertattack\Webtrees\Module\MediaManager\model\ImageFile;
use Illuminate\Support\Collection;
use Intervention\Image\Image;
use Intervention\Image\ImageManager;

/**
 * @var string $title
 * @var Collection $mediaFolders
 * @var Collection $filesOnDisk
 * @var ImageManager $imageManager
 * @var ImageFile $imageFile
 */

?>
<?= view('components/breadcrumbs', ['links' => [route(ControlPanel::class) => I18N::translate('Control panel'), $title]]) ?>

<div class="row mb-3">
    Hello World!
    <--?php print($mediaFolders["media/"]) ?>
    <?php print($mediaFolders->values()) ?>
    <?php print($filesOnDisk) ?>
    Width:
    <?php
        print($imageFile->image->width());
    ?>
    Size: <?= $imageFile->fileSize ?>
</div>
